Repository radicalplatforms/shafa, pull requests merged in 2024-02, with the labels that each got.

#33 docs: updated README
  README.md
Labels: docs

#32 feat: add drizzle database connection as middleware
  hono/.eslintrc.js
  hono/.prettierrc.json
  hono/jest.config.js
  hono/package-lock.json
  hono/package.json
  hono/src/index.ts
  hono/src/schema.ts
  hono/src/service/items.ts
  hono/src/service/outfits.ts
  hono/src/utils/injectDB.ts
  hono/test/items.test.ts
  hono/tsconfig.json
Labels: feat

#46 fix: patched db undefined bug
  hono/src/utils/injectDB.ts
Labels: bug, backend

#51 fix: patched authorUsername body bug on backend
  .github/workflows/hono_format.yml
  hono/package.json
  hono/src/service/items.ts
  hono/src/service/outfits.ts
  hono/tsconfig.json
Labels: bug, backend

#52 feat: combined github action workflows
  .github/workflows/hono_deploy_production.yml
  .github/workflows/hono_deploy_stage.yml
  .github/workflows/hono_format.yml
  .github/workflows/hono_integration_checks.yml
  .github/workflows/hono_jest.yml
Labels: feat, backend

#47 test: implement mock database
  .github/workflows/hono_integration_checks.yml
  hono/.gitignore
  hono/jest.config.js
  hono/package-lock.json
  hono/package.json
  hono/test/factory/items.ts
  hono/test/items.test.ts
  hono/test/utils/cleanup-test-db.sql
  hono/wrangler.toml
Labels: test, backend

#56 feat: migrate d1 to neon, polish APIs
  .github/workflows/hono_deploy_production.yml
  .github/workflows/hono_deploy_stage.yml
  .github/workflows/hono_integration.yml
  .github/workflows/hono_integration_checks.yml
  .github/workflows/hono_teardown.yml
  README.md
  hono/.dev.vars.example
  hono/.gitignore
  hono/drizzle.config.json
  hono/drizzle/0000_rare_jigsaw.sql
  hono/drizzle/0001_light_annihilus.sql
  hono/drizzle/0002_fluffy_malcolm_colcord.sql
  hono/drizzle/0003_milky_captain_marvel.sql
  hono/drizzle/meta/0001_snapshot.json
  hono/drizzle/meta/0002_snapshot.json
  hono/drizzle/meta/0003_snapshot.json
  hono/drizzle/meta/_journal.json
  hono/jest.config.js
  hono/migrate.ts
  hono/package-lock.json
  hono/package.json
  hono/src/drizzle/0000_illegal_mister_fear.sql
  hono/src/drizzle/meta/0000_snapshot.json
  hono/src/drizzle/meta/_journal.json
  hono/src/index.ts
  hono/src/schema.ts
  hono/src/service/items.ts
  hono/src/service/outfits.ts
  hono/src/services/items.ts
  hono/src/services/outfits.ts
  hono/src/utils/injectDB.ts
  hono/test/factory/items.ts
  hono/test/integration/items_outfits.integration.test.ts
  hono/test/items.test.ts
  hono/test/preflight/local.preflight.test.ts
  hono/test/preflight/neon.preflight.test.ts
  hono/test/preflight/preflight.test.ts
  hono/test/preflight/remote.preflight.test.ts
  hono/test/smoke/hono.smoke.test.ts
  hono/test/smoke/items.smoke.test.ts
  hono/test/smoke/outfits.smoke.test.ts
  hono/test/unit/items.unit.test.ts
  hono/test/unit/outfits.unit.test.ts
  hono/test/utils/clean-db.sql
  hono/test/utils/cleanup-test-db.sql
  hono/test/utils/db.ts
  hono/test/utils/factory/items.ts
  hono/test/utils/factory/outfits.ts
  hono/test/utils/global-setup.ts
  hono/test/utils/global-teardown.ts
  hono/test/utils/seeds/items-simple.sql
  hono/test/utils/seeds/outfits-simple.sql
  hono/tsconfig.json
  hono/wrangler.toml
Labels: feat, backend

#57 fix: patched prod, pr closing workflow runs
  .github/workflows/hono_deploy_production.yml
  .github/workflows/hono_teardown.yml
Labels: bug, backend

#99 chore: refactor injectDB to inject-db
  hono/src/services/items.ts
  hono/src/services/outfits.ts
  hono/src/utils/inject-db.ts
  hono/test/integration/items_outfits.integration.test.ts
  hono/test/preflight/local.preflight.test.ts
  hono/test/smoke/items.smoke.test.ts
  hono/test/smoke/outfits.smoke.test.ts
  hono/test/unit/items.unit.test.ts
  hono/test/unit/outfits.unit.test.ts
Labels: refactor, backend

#100 chore: refactor items_outfits.integration.test.ts to refactor items-outfits.integration.test.ts
  hono/test/integration/items-outfits.integration.test.ts
Labels: refactor, backend
