Repository radicalplatforms/shafa, pull requests merged in 2024-03, with the labels that each got.

#103 docs: updated README with refined purpose
  README.md
Labels: docs

#102 feat: implemented faker, reworked factory on backend
  README.md
  hono/package-lock.json
  hono/package.json
  hono/src/drizzle/0001_dusty_nighthawk.sql
  hono/src/drizzle/meta/0001_snapshot.json
  hono/src/drizzle/meta/_journal.json
  hono/src/schema.ts
  hono/src/services/items.ts
  hono/src/services/outfits.ts
  hono/test/integration/items-outfits.integration.test.ts
  hono/test/preflight/local.preflight.test.ts
  hono/test/smoke/items.smoke.test.ts
  hono/test/smoke/outfits.smoke.test.ts
  hono/test/unit/items.unit.test.ts
  hono/test/unit/outfits.unit.test.ts
  hono/test/utils/db.ts
  hono/test/utils/factory/items-outfits.ts
  hono/test/utils/factory/items.ts
  hono/test/utils/factory/outfits.ts
  hono/test/utils/seeds/basic-small-seed.ts
  hono/test/utils/seeds/items-simple.sql
  hono/test/utils/seeds/outfits-simple.sql
Labels: feat, test, backend

#106 feat: added workflow environments
  .github/workflows/hono_deploy_production.yml
  .github/workflows/hono_integration.yml
  .github/workflows/hono_teardown.yml
Labels: feat, chore

#108 feat: add additional smoke tests
  hono/src/index.ts
  hono/test/smoke/hono.smoke.test.ts
Labels: test, backend

#109 feat: added smart comments for PRs
  .github/workflows/pr_smart_comments.yml
Labels: feat, style

#110 feat: add pagination to get items
  hono/src/services/items.ts
  hono/test/smoke/items.smoke.test.ts
  hono/test/utils/seeds/basic-small-seed.ts
Labels: backend

#117 feat: added preflight user test skeleton
  hono/test/preflight/preflight.test.ts
Labels: test, chore, backend

#118 feat: create frontend GitHub actions workflows, added new frontend template
  .github/workflows/hono_integration.yaml
  .github/workflows/next_integration.yaml
  .github/workflows/pr_smart_comments.yaml
  .github/workflows/production_deploy.yaml
  .github/workflows/staging_teardown.yaml
  .github/workflows/utils/pages_teardown.sh
  next/.eslintrc.json
  next/.gitignore
  next/README.md
  next/env.d.ts
  next/jsconfig.json
  next/next.config.js
  next/next.config.mjs
  next/package-lock.json
  next/package.json
  next/postcss.config.js
  next/prettier.config.js
  next/public/next.svg
  next/public/vercel.svg
  next/src/app/favicon.ico
  next/src/app/globals.css
  next/src/app/layout.tsx
  next/src/app/not-found.tsx
  next/src/app/page.tsx
  next/src/components/Outfit.jsx
  next/src/components/OutfitItem.jsx
  next/src/pages/_app.jsx
  next/src/pages/_document.jsx
  next/src/pages/index.jsx
  next/src/pages/outfits.jsx
  next/src/styles/tailwind.css
  next/tailwind.config.js
  next/tailwind.config.ts
  next/tsconfig.json
  next/wrangler.toml
Labels: frontend, devex

#119 fix: patched prod deploy indenting
  .github/workflows/production_deploy.yaml
Labels: bug, frontend, devex
